services:
  squares-db:
    image: postgres:16-alpine
    container_name: squares-db
    restart: always
    environment:
      POSTGRES_DB: SquaresDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: squareDB%08
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SquaresDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  squares-api:
    image: squares-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: squares-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=squares-db;Port=5432;Database=SquaresDb;Username=postgres;Password=squareDB%08
    depends_on:
      squares-db:
        condition: service_healthy

volumes:
  postgres_data: